#week 4 :turtle graphics
import turtle # allows us touse the code from the turtle libary/module

ken = turtle.Turtle() #creates an instance of the class Turtle 
ken .shape("turtle")
ken .color("purple")

#ken.forward(100)
#ken.backward(200)
#ken.right(90)
for x in range(0,4):
    ken.penup ()
    ken.forward (150)
    ken.pendown ()
    ken.begin_fill()
    ken.forward(100)
    ken.right(90)
    ken.forward(100)
    ken.right(90)
    ken.end_fill()
    ken.penup()
    ken.forward(100)
    ken.right(90)
    ken.forward(100)
    ken.left(90)
    ken.forward(100)
    ken.right(90)
    ken.forward(100)

    ken.penup ()
    ken.forward (200)
    ken.pendown ()
    ken.begin_fill()
    ken.forward(150)
    ken.right(180)
    ken.forward(150)
    ken.right(180)
    ken.end_fill()
    ken.penup()
    ken.forward(150)
    ken.right(180)
    ken.forward(150)
    ken.left(180)
    ken.forward(150)
    ken.right(180)
    ken.forward(150)

#makig a squre with no corners
kin = turtle.Turtle()
kin.color("blue")
kin.shape("turtle")

for x in range(0,4):
    kin.penup ()
    kin.forward (100)
    kin.pendown ()
    kin.begin_fill()
    kin.forward(100)
    kin.right(90)
    kin.forward(75)
    kin.right(90)
    kin.end_fill()
    kin.penup()
    kin.forward(75)
    kin.right(90)
    kin.forward(75)
    kin.left(90)
    kin.forward(75)
    kin.right(90)
    kin.forward(75)
    kin.penup ()
    kin.forward (100)
    kin.pendown ()
    kin.begin_fill()
    kin.forward(100)
    kin.right(90)
    kin.forward(75)
    kin.right(90)
    kin.end_fill()
    kin.penup()
    kin.forward(75)
    kin.right(90)
    kin.forward(75)
    kin.left(90)
    kin.forward(75)
    kin.right(90)
    kin.forward(75)
    
